steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
artifacts:
  objects:
    location: 'gs://thebookie'
    paths: ["/workspace/Locanda_target/Locanda.war"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'target/Locanda_target/WEB-INF/appengine-web.xml']

